### ISSUE TITLE
Vertical scroll

### ISSUE THREAD

**Issue by rgvillanueva28** [oelshocht/react-table-scrollbar#15]
Add support for vertical scrolling

**Comment by oelshocht** [comment]
@rgvillanueva28, can you elaborate on this issue? (react-table-scrollbar is supposed to support vertical scrolling already).

**Comment by rgvillanueva28** [comment]
What I mean Sir is to add support for fixed row on vertical scrolling.

**Comment by oelshocht** [comment]
I don't understand. This is precisely what react-table-scrollbar does. Can you give an example?
